name: aquaticket
description: A new Flutter project.
publish_to: 'none' # this prevents accidental publishing to pub.dev

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


