name: aquaticket
description: A new Flutter project.
publish_to: 'none' # this prevents accidental publishing to pub.dev

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.13.1
  firebase_storage: ^11.5.1
  image_picker: ^1.0.4
  firebase_messaging: ^14.7.1
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


