// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMrzLsKCZSpr80y21wtsp8bE7pmH5fJtM',
    appId: '1:243345829576:android:2f03163466106ef4a83ffd',
    messagingSenderId: '243345829576',
    projectId: 'aquaticket-89725',
    storageBucket: 'aquaticket-89725.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5f0EUUQUw8mb8t7zJ_B_uXW2adKyWFSs',
    appId: '1:243345829576:web:aa0eb6e08aab80d3a83ffd',
    messagingSenderId: '243345829576',
    projectId: 'aquaticket-89725',
    authDomain: 'aquaticket-89725.firebaseapp.com',
    storageBucket: 'aquaticket-89725.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB91zd3p5lvOxKIrwKL2V9J9ojh9OHYcvI',
    appId: '1:243345829576:ios:5ff0131f7248a372a83ffd',
    messagingSenderId: '243345829576',
    projectId: 'aquaticket-89725',
    storageBucket: 'aquaticket-89725.firebasestorage.app',
    iosBundleId: 'com.pmg.aquaticket',
  );

}